[tool.pylint.messages_control]
disable = [
    "redefined-outer-name",
    "not-context-manager"
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
    "ignore:.*some specific warning message.*"
]