"""
Module for rewriting queries using various techniques.

This module provides functionality to rewrite a given query using different 
query rewriting techniques, leveraging a language model to generate the rewritten 
queries. Currently, the available techniques include 'zero_shot' and 'hyde'. 
Additional techniques may be added in the future.

Dependencies:
- utils.query: For building prompts and interacting with the language model.
- utils.utils: For parsing the model's response into a usable format.
- exceptions.exceptions: For handling custom exceptions related to unknown 
  query rewriting techniques.

Usage:
------
The main function `rewrite_query` can be used to generate rewritten queries 
based on the selected technique.
"""

from exceptions.exceptions import UnknownQueryRewritingTechnique
from utils.query import build_prompt, llm
from utils.utils import parse_list_response


def rewrite_query(
    query, prompt_template_path, technique, model_choice="openai/gpt-3.5-turbo"
):
    """
    Rewrites a query using the specified technique and a language model.

    This function takes an input query and rewrites it according to the selected
    technique. The rewritten query is generated by constructing a prompt from
    the provided template and querying a language model. The current available
    techniques are 'zero_shot' and 'hyde'. Additional techniques will be added
    to this function as they are developed.

    Parameters:
    -----------
    query : str
        The original query string to be rewritten.
    prompt_template_path : str
        The path to the prompt template file used for generating the prompt.
    technique : str
        The technique to be used for rewriting the query. Must be one of:
        'zero_shot', 'hyde'. If an unsupported technique is provided, an
        `UnknownQueryRewritingTechnique` exception is raised.
    model_choice : str, optional
        The language model to use for generating the rewritten query,
        default is "openai/gpt-3.5-turbo".

    Returns:
    --------
    list of str
        The rewritten query or queries based on the selected technique.
        For 'zero_shot', the response is parsed into a list. For 'hyde',
        the response is returned as a single-item list.

    Raises:
    -------
    UnknownQueryRewritingTechnique
        If the provided technique is not recognized.

    Notes:
    ------
    Additional rewriting techniques will be incorporated into this function
    in future updates.
    """
    if technique not in ["zero_shot", "hyde"]:
        raise UnknownQueryRewritingTechnique(
            """`technique` should take one of the following: [
                'zero_shot', 'hyde', ..
            ]"""
        )

    prompt = build_prompt(prompt_template_path, query=query)
    response = llm(prompt=prompt, model_choice=model_choice)

    if technique == "zero_shot":
        return parse_list_response(response[0])

    # if technique == "hyde":
    return [response[0]]
